<script setup>
import { reactive } from 'vue'
import { Head, Link, router } from '@inertiajs/vue3'
import { FileClock, Filter } from 'lucide-vue-next'
import MainLayout from '@/presentation/layouts/MainLayout.vue'

const props = defineProps({ logs: { type: Object, required: true }, units: { type: Array, required: true }, actionOptions: { type: Array, required: true }, filters: { type: Object, required: true } })
const filters = reactive({ ...props.filters })
const apply = () => router.get('/admin/audit-logs', filters, { preserveState: true, replace: true })
const formatDate = (value) => new Intl.DateTimeFormat('id-ID', { dateStyle: 'medium', timeStyle: 'short', timeZone: 'Asia/Jakarta' }).format(new Date(value))
const formatJson = (value) => JSON.stringify(value ?? {}, null, 2)
const actionLabel = (value) => ({ 'unit.created': 'Unit dibuat', 'unit.updated': 'Unit diperbarui', 'account.created': 'Akun dibuat', 'account.updated': 'Akun diperbarui', 'account.status_changed': 'Status akun', 'account.password_reset': 'Reset kata sandi' }[value] ?? value)
</script>
<template>
  <Head title="Audit Log"/><MainLayout>
    <div class="mb-6"><p class="text-sm font-medium text-orange-600">Tata kelola</p><h2 class="mt-1 text-2xl font-semibold text-slate-950">Audit Log</h2><p class="mt-2 text-sm text-slate-600">Riwayat perubahan yang tidak dapat diedit atau dihapus dari aplikasi.</p></div>
    <form class="mb-5 grid gap-3 rounded-xl border border-slate-200 bg-white p-4 shadow-sm xl:grid-cols-[1fr_1fr_11rem_11rem_auto]" @submit.prevent="apply"><select v-model="filters.action" class="h-11 rounded-lg border border-slate-300 px-3 text-sm"><option value="">Semua aktivitas</option><option v-for="action in actionOptions" :key="action" :value="action">{{actionLabel(action)}}</option></select><select v-model="filters.unit_kerja_id" class="h-11 rounded-lg border border-slate-300 px-3 text-sm"><option value="">Semua unit</option><option v-for="unit in units" :key="unit.id" :value="String(unit.id)">{{unit.code}}</option></select><input v-model="filters.date_from" type="date" class="h-11 rounded-lg border border-slate-300 px-3 text-sm" aria-label="Tanggal mulai"><input v-model="filters.date_to" type="date" class="h-11 rounded-lg border border-slate-300 px-3 text-sm" aria-label="Tanggal akhir"><button class="inline-flex h-11 items-center justify-center gap-2 rounded-lg bg-[#171650] px-4 text-sm font-medium text-white"><Filter :size="17"/>Terapkan</button></form>
    <section class="overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm"><div v-if="logs.data.length" class="divide-y divide-slate-100"><article v-for="log in logs.data" :key="log.id" class="p-5"><div class="grid gap-4 lg:grid-cols-[11rem_1fr_12rem_auto]"><div><p class="text-xs text-slate-500">Waktu</p><p class="mt-1 text-sm font-medium">{{formatDate(log.created_at)}} WIB</p></div><div><p class="text-xs text-slate-500">Aktivitas</p><p class="mt-1 text-sm font-semibold text-slate-900">{{actionLabel(log.action)}}</p><p class="mt-1 text-xs text-slate-500">{{log.auditable_type?.split('\\').pop()}} #{{log.auditable_id}}</p></div><div><p class="text-xs text-slate-500">Pelaku / Unit</p><p class="mt-1 truncate text-sm">{{log.actor?.name ?? 'Sistem'}}</p><p class="mt-1 text-xs text-slate-500">{{log.unit_kerja?.code ?? 'Pusat'}}</p></div><details class="self-start"><summary class="cursor-pointer rounded-lg border border-slate-300 px-3 py-2 text-xs font-medium text-slate-700">Lihat perubahan</summary><div class="mt-3 grid gap-3 sm:grid-cols-2 lg:absolute lg:right-10 lg:z-10 lg:w-[38rem] lg:rounded-xl lg:border lg:bg-white lg:p-4 lg:shadow-xl"><div><p class="mb-1 text-xs font-semibold text-slate-500">Sebelum</p><pre class="max-h-52 overflow-auto rounded bg-slate-950 p-3 text-xs text-slate-100">{{formatJson(log.old_values)}}</pre></div><div><p class="mb-1 text-xs font-semibold text-slate-500">Sesudah</p><pre class="max-h-52 overflow-auto rounded bg-slate-950 p-3 text-xs text-slate-100">{{formatJson(log.new_values)}}</pre></div></div></details></div></article></div><div v-else class="py-16 text-center"><FileClock :size="30" class="mx-auto text-slate-400"/><h3 class="mt-3 font-semibold">Belum ada catatan audit</h3><p class="mt-2 text-sm text-slate-500">Aktivitas yang sesuai filter akan muncul di sini.</p></div><div v-if="logs.links.length>3" class="flex gap-1 border-t p-4"><Link v-for="link in logs.links" :key="link.label" :href="link.url||'#'" class="rounded border px-3 py-2 text-xs" :class="link.active?'bg-[#171650] text-white':'text-slate-600'">{{link.label.replace('&laquo; Previous','Sebelumnya').replace('Next &raquo;','Berikutnya')}}</Link></div></section>
  </MainLayout>
</template>
